services:
  # NGINX : Point d'entrée qui gère les requêtes externes.
  nginx:
    image: nginx:1.27-alpine
    container_name: fastmcp_nginx
    ports:
      - '${HOST_PORT:-8080}:8080'
    volumes:
      # La configuration Nginx est requise (voir ci-dessous)
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastmcp-server
    restart: unless-stopped
    networks:
      - app_net

  # SERVEUR FastMCP : Ne gère que les requêtes directes.
  fastmcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastmcp_server_app
    env_file: .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_net

  # WORKER : Gère les tâches asynchrones en arrière-plan.
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    # La commande pour démarrer spécifiquement le worker
    command: pnpm run start:worker
    container_name: fastmcp_worker
    env_file: .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_net

  # REDIS : File d'attente pour BullMQ.
  redis:
    image: redis:7.2-alpine
    container_name: fastmcp_redis
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD?Variable REDIS_PASSWORD non définie dans .env}
    healthcheck:
      test: ['CMD', 'redis-cli', '-h', '127.0.0.1', '-p', '6379', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_net

volumes:
  redis_data:

networks:
  app_net:
