# docker-compose.yml (Version Finale sans Nginx)
services:
  fastmcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastmcp_server_app
    ports:
      # Expose le port 8080 du conteneur directement sur le port 8080 de votre machine hôte.
      - '8080:8080'
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run start:worker
    container_name: fastmcp_worker
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_net

  redis:
    image: redis:7.2-alpine
    container_name: fastmcp_redis
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD?Variable REDIS_PASSWORD non définie dans .env}
    healthcheck:
      test: ['CMD', 'redis-cli', '-h', '127.0.0.1', '-p', '6379', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_net

volumes:
  redis_data:

networks:
  app_net:
